### ISSUE TITLE
from aniachi.systemUtils import Welcome as W ModuleNotFoundError: No module named 'aniachi'

### ISSUE THREAD

**Issue by dinesh1299** [bygregonline/django_hl7_rest#1]
Could you provide me the pypi link to install this package, I've researched about this but couldn't find one

**Comment by bygregonline** [comment]
pull the latest version
docker build -t your_name/hl7:latest .
docker run -d -p 8000:8000 your_name/hl7:latest
goto your browser localhost:8000



also

a new requirements.txt file has been added with dependencies
